// This file is auto-generated by @hey-api/openapi-ts

/**
 * ProfileInit
 * Profile data from Auth0 ID token for user initialization.
 */
export type ProfileInit = {
  /**
   * Email
   */
  email?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Nickname
   */
  nickname?: string | null
}

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Auth0 Sub
   * Auth0 subject identifier
   */
  auth0_sub: string
  /**
   * Email
   * User's email address
   */
  email?: string | null
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Roles
   * List of role identifiers
   */
  roles?: Array<string>
  /**
   * Is Active
   * Whether the user is active
   */
  is_active?: boolean
}

/**
 * UserProfile
 */
export type UserProfile = {
  /**
   * Sub
   */
  sub: string
  /**
   * Name
   */
  name?: string | null
  /**
   * Nickname
   */
  nickname?: string | null
  /**
   * Email
   */
  email?: string | null
  /**
   * Picture
   */
  picture?: string | null
  /**
   * Bio
   */
  bio?: string | null
  /**
   * Email Verified
   */
  email_verified?: boolean | null
  /**
   * Roles
   * User's roles
   */
  roles?: Array<string>
  /**
   * Is Admin
   * Whether user has admin role
   */
  is_admin?: boolean
  /**
   * Is Active
   * Whether user is active
   */
  is_active?: boolean
}

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Nickname
   * User's nickname
   */
  nickname?: string | null
  /**
   * Picture
   * URL to user's profile picture
   */
  picture?: string | null
  /**
   * Bio
   * User's biography
   */
  bio?: string | null
}

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string
  /**
   * Auth0 Sub
   */
  auth0_sub: string
  /**
   * Email
   */
  email?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Roles
   */
  roles: Array<string>
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   * User's email address
   */
  email?: string | null
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Roles
   * List of role identifiers
   */
  roles?: Array<string> | null
  /**
   * Is Active
   * Whether the user is active
   */
  is_active?: boolean | null
}

export type ValidationErrorItem = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ProblemDetails = {
  type: string
  code?: string
  title: string
  status: number
  detail?: string
  instance?: string
  errors?: Array<ValidationErrorItem>
}

export type HealthHealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/healthz'
}

export type HealthHealthCheckErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type HealthHealthCheckError = HealthHealthCheckErrors[keyof HealthHealthCheckErrors]

export type HealthHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthReadinessCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/readyz'
}

export type HealthReadinessCheckErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type HealthReadinessCheckError = HealthReadinessCheckErrors[keyof HealthReadinessCheckErrors]

export type HealthReadinessCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type UsersUpdateUserProfileData = {
  body: UserProfileUpdate
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UsersUpdateUserProfileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersUpdateUserProfileError =
  UsersUpdateUserProfileErrors[keyof UsersUpdateUserProfileErrors]

export type UsersUpdateUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserProfile
}

export type UsersUpdateUserProfileResponse =
  UsersUpdateUserProfileResponses[keyof UsersUpdateUserProfileResponses]

export type UsersGetCurrentUserProfileData = {
  /**
   * Profile Init
   */
  body?: ProfileInit | null
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UsersGetCurrentUserProfileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetCurrentUserProfileError =
  UsersGetCurrentUserProfileErrors[keyof UsersGetCurrentUserProfileErrors]

export type UsersGetCurrentUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserProfile
}

export type UsersGetCurrentUserProfileResponse =
  UsersGetCurrentUserProfileResponses[keyof UsersGetCurrentUserProfileResponses]

export type UsersGetAuth0ManagementUrlData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users/auth0-management-url'
}

export type UsersGetAuth0ManagementUrlErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetAuth0ManagementUrlError =
  UsersGetAuth0ManagementUrlErrors[keyof UsersGetAuth0ManagementUrlErrors]

export type UsersGetAuth0ManagementUrlResponses = {
  /**
   * Response Users-Get Auth0 Management Url
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type UsersGetAuth0ManagementUrlResponse =
  UsersGetAuth0ManagementUrlResponses[keyof UsersGetAuth0ManagementUrlResponses]

export type UsersListUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: '/api/v1/users/'
}

export type UsersListUsersErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersListUsersError = UsersListUsersErrors[keyof UsersListUsersErrors]

export type UsersListUsersResponses = {
  /**
   * Response Users-List Users
   * Successful Response
   */
  200: Array<UserRead>
}

export type UsersListUsersResponse = UsersListUsersResponses[keyof UsersListUsersResponses]

export type UsersCreateUserData = {
  body: UserCreate
  path?: never
  query?: never
  url: '/api/v1/users/'
}

export type UsersCreateUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
  /**
   * Successful Response
   */
  201: UserRead
}

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersDeleteUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersGetUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersGetUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetUserError = UsersGetUserErrors[keyof UsersGetUserErrors]

export type UsersGetUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersGetUserResponse = UsersGetUserResponses[keyof UsersGetUserResponses]

export type UsersUpdateUserData = {
  body: UserUpdate
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersUpdateUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}
