// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod'

/**
 * ProfileInit
 * Profile data from Auth0 ID token for user initialization.
 */
export const zProfileInit = z
  .object({
    email: z.optional(z.union([z.email(), z.null()])),
    name: z.optional(z.union([z.string(), z.null()])),
    nickname: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Profile data from Auth0 ID token for user initialization.',
  })

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  auth0_sub: z.string().register(z.globalRegistry, {
    description: 'Auth0 subject identifier',
  }),
  email: z.optional(z.union([z.email(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  roles: z.optional(
    z.array(z.string()).register(z.globalRegistry, {
      description: 'List of role identifiers',
    }),
  ),
  is_active: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether the user is active',
      }),
    )
    .default(true),
})

/**
 * UserProfile
 */
export const zUserProfile = z.object({
  sub: z.string(),
  name: z.optional(z.union([z.string(), z.null()])),
  nickname: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  picture: z.optional(z.union([z.url().min(1).max(2083), z.null()])),
  bio: z.optional(z.union([z.string(), z.null()])),
  email_verified: z.optional(z.union([z.boolean(), z.null()])),
  roles: z.optional(
    z.array(z.string()).register(z.globalRegistry, {
      description: "User's roles",
    }),
  ),
  is_admin: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether user has admin role',
      }),
    )
    .default(false),
  is_active: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether user is active',
      }),
    )
    .default(true),
})

/**
 * UserProfileUpdate
 */
export const zUserProfileUpdate = z.object({
  name: z.optional(z.union([z.string().max(100), z.null()])),
  nickname: z.optional(z.union([z.string().max(50), z.null()])),
  picture: z.optional(z.union([z.url().min(1).max(2083), z.null()])),
  bio: z.optional(z.union([z.string().max(500), z.null()])),
})

/**
 * UserRead
 */
export const zUserRead = z.object({
  id: z.uuid(),
  auth0_sub: z.string(),
  email: z.optional(z.union([z.email(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  roles: z.array(z.string()),
  is_active: z.boolean(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
  email: z.optional(z.union([z.email(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  roles: z.optional(z.union([z.array(z.string()), z.null()])),
  is_active: z.optional(z.union([z.boolean(), z.null()])),
})

export const zValidationErrorItem = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

export const zProblemDetails = z.object({
  type: z.url().default('about:blank'),
  code: z.optional(z.string()),
  title: z.string(),
  status: z.int(),
  detail: z.optional(z.string()),
  instance: z.optional(z.string()),
  errors: z.optional(z.array(zValidationErrorItem)),
})

export const zHealthHealthCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zHealthReadinessCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zUsersUpdateUserProfileData = z.object({
  body: zUserProfileUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersUpdateUserProfileResponse = zUserProfile

export const zUsersGetCurrentUserProfileData = z.object({
  body: z.optional(z.union([zProfileInit, z.null()])),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersGetCurrentUserProfileResponse = zUserProfile

export const zUsersGetAuth0ManagementUrlData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Users-Get Auth0 Management Url
 * Successful Response
 */
export const zUsersGetAuth0ManagementUrlResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersListUsersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      skip: z.optional(z.int()).default(0),
      limit: z.optional(z.int()).default(100),
    }),
  ),
})

/**
 * Response Users-List Users
 * Successful Response
 */
export const zUsersListUsersResponse = z.array(zUserRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersCreateUserData = z.object({
  body: zUserCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersCreateUserResponse = zUserRead

export const zUsersDeleteUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zUserRead

export const zUsersGetUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersGetUserResponse = zUserRead

export const zUsersUpdateUserData = z.object({
  body: zUserUpdate,
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserRead
