// This file is auto-generated by @hey-api/openapi-ts
import * as z from 'zod'

/**
 * AffectedBookingInfo
 */
export const zAffectedBookingInfo = z.object({
  booking_id: z.uuid(),
  user_id: z.uuid(),
  slot_title: z.string(),
  slot_date: z.iso.date(),
  slot_start_time: z.iso.time().nullish(),
  slot_end_time: z.iso.time().nullish(),
})

/**
 * BookingCreate
 *
 * User only provides the slot and optional notes. user_id is set server-side.
 */
export const zBookingCreate = z
  .object({
    duty_slot_id: z.uuid(),
    notes: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'User only provides the slot and optional notes. user_id is set server-side.',
  })

/**
 * BookingRead
 */
export const zBookingRead = z.object({
  duty_slot_id: z.uuid().nullish(),
  user_id: z.uuid(),
  status: z.enum(['confirmed', 'cancelled']).optional().default('confirmed'),
  notes: z.string().nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  cancellation_reason: z.string().nullish(),
  cancelled_slot_title: z.string().nullish(),
  cancelled_slot_date: z.iso.date().nullish(),
  cancelled_slot_start_time: z.iso.time().nullish(),
  cancelled_slot_end_time: z.iso.time().nullish(),
  cancelled_event_name: z.string().nullish(),
})

/**
 * BookingReminderCreate
 *
 * User provides the offset and channels; remind_at is computed server-side.
 */
export const zBookingReminderCreate = z
  .object({
    offset_minutes: z.union([
      z.literal(15),
      z.literal(30),
      z.literal(60),
      z.literal(120),
      z.literal(180),
      z.literal(360),
      z.literal(720),
      z.literal(1440),
      z.literal(2880),
    ]),
    channels: z
      .array(z.enum(['email', 'push', 'telegram']))
      .min(1)
      .optional()
      .default(['push']),
  })
  .register(z.globalRegistry, {
    description: 'User provides the offset and channels; remind_at is computed server-side.',
  })

/**
 * BookingReminderRead
 */
export const zBookingReminderRead = z.object({
  id: z.uuid(),
  booking_id: z.uuid(),
  offset_minutes: z.int(),
  channels: z.array(z.string()),
  remind_at: z.iso.datetime(),
  status: z.enum(['pending', 'sent', 'cancelled', 'expired']),
  created_at: z.iso.datetime(),
})

/**
 * BookingReminderListResponse
 */
export const zBookingReminderListResponse = z.object({
  items: z.array(zBookingReminderRead),
})

/**
 * BookingUpdate
 */
export const zBookingUpdate = z.object({
  status: z.enum(['confirmed', 'cancelled']).nullish(),
  notes: z.string().nullish(),
  cancellation_reason: z.string().nullish(),
})

/**
 * BookingsByHour
 */
export const zBookingsByHour = z.object({
  hour: z.int(),
  booking_count: z.int(),
})

/**
 * BookingsTrendPoint
 */
export const zBookingsTrendPoint = z.object({
  date: z.iso.date(),
  confirmed: z.int(),
  cancelled: z.int(),
})

/**
 * CalendarFeedRead
 *
 * Response for calendar feed management endpoints.
 */
export const zCalendarFeedRead = z
  .object({
    id: z.uuid(),
    feed_url: z.string(),
    is_enabled: z.boolean(),
    last_accessed_at: z.iso.datetime().nullish(),
    created_at: z.iso.datetime(),
  })
  .register(z.globalRegistry, {
    description: 'Response for calendar feed management endpoints.',
  })

/**
 * CategoryBreakdown
 */
export const zCategoryBreakdown = z.object({
  category: z.string().nullable(),
  slot_count: z.int(),
  total_capacity: z.int(),
  confirmed_bookings: z.int(),
  fill_rate: z.number(),
})

/**
 * DashboardBookingItem
 *
 * Booking with inline slot info for calendar display — avoids N+1.
 */
export const zDashboardBookingItem = z
  .object({
    id: z.uuid(),
    slot_id: z.uuid(),
    date: z.iso.date(),
    title: z.string(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Booking with inline slot info for calendar display — avoids N+1.',
  })

/**
 * DashboardEvent
 *
 * Slim event for the dashboard calendar.
 */
export const zDashboardEvent = z
  .object({
    id: z.uuid(),
    name: z.string(),
    status: z.string(),
    description: z.string().nullish(),
    location: z.string().nullish(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
  })
  .register(z.globalRegistry, {
    description: 'Slim event for the dashboard calendar.',
  })

/**
 * DashboardEventGroup
 *
 * Slim event group for the dashboard calendar.
 */
export const zDashboardEventGroup = z
  .object({
    id: z.uuid(),
    name: z.string(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
  })
  .register(z.globalRegistry, {
    description: 'Slim event group for the dashboard calendar.',
  })

/**
 * DashboardFeedResponse
 */
export const zDashboardFeedResponse = z.object({
  events: z.array(zDashboardEvent),
  event_count: z.int(),
  event_groups: z.array(zDashboardEventGroup),
  bookings: z.array(zDashboardBookingItem),
  booking_count: z.int(),
  pending_user_count: z.int().nullish(),
})

/**
 * DemoDataCreatedResponse
 */
export const zDemoDataCreatedResponse = z.object({
  event_groups_created: z.int(),
  events_created: z.int(),
  users_created: z.int(),
  duty_slots_created: z.int(),
  bookings_created: z.int(),
})

/**
 * DemoDataDeletedResponse
 */
export const zDemoDataDeletedResponse = z.object({
  events_deleted: z.int(),
  event_groups_deleted: z.int(),
  users_deleted: z.int(),
  duty_slots_deleted: z.int(),
  bookings_deleted: z.int(),
})

/**
 * DemoDataParams
 */
export const zDemoDataParams = z.object({
  num_events: z.int().gte(1).lte(50).optional().default(10),
  num_event_groups: z.int().gte(0).lte(10).optional().default(3),
  num_users: z.int().gte(0).lte(20).optional().default(5),
  num_slots_per_event: z.int().gte(1).lte(20).optional().default(4),
  publish_events: z.boolean().optional().default(true),
})

/**
 * DutySlotCreate
 */
export const zDutySlotCreate = z.object({
  event_id: z.uuid(),
  title: z.string(),
  description: z.string().nullish(),
  date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  max_bookings: z.int().optional().default(1),
  batch_id: z.uuid().nullish(),
})

/**
 * DutySlotRead
 */
export const zDutySlotRead = z.object({
  event_id: z.uuid(),
  title: z.string(),
  description: z.string().nullish(),
  date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  max_bookings: z.int().optional().default(1),
  batch_id: z.uuid().nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  current_bookings: z.int().optional().default(0),
  is_booked_by_me: z.boolean().optional().default(false),
})

/**
 * DutySlotListResponse
 */
export const zDutySlotListResponse = z.object({
  items: z.array(zDutySlotRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * DutySlotSummary
 *
 * Lightweight slot info nested inside a booking response.
 */
export const zDutySlotSummary = z
  .object({
    id: z.uuid(),
    event_id: z.uuid(),
    title: z.string(),
    date: z.iso.date(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
    location: z.string().nullish(),
    category: z.string().nullish(),
    event_name: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Lightweight slot info nested inside a booking response.',
  })

/**
 * BookingReadWithSlot
 *
 * BookingRead enriched with nested slot + event name (for /me endpoint).
 */
export const zBookingReadWithSlot = z
  .object({
    duty_slot_id: z.uuid().nullish(),
    user_id: z.uuid(),
    status: z.enum(['confirmed', 'cancelled']).optional().default('confirmed'),
    notes: z.string().nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    cancellation_reason: z.string().nullish(),
    cancelled_slot_title: z.string().nullish(),
    cancelled_slot_date: z.iso.date().nullish(),
    cancelled_slot_start_time: z.iso.time().nullish(),
    cancelled_slot_end_time: z.iso.time().nullish(),
    cancelled_event_name: z.string().nullish(),
    duty_slot: zDutySlotSummary.nullish(),
  })
  .register(z.globalRegistry, {
    description: 'BookingRead enriched with nested slot + event name (for /me endpoint).',
  })

/**
 * DutySlotUpdate
 */
export const zDutySlotUpdate = z.object({
  title: z.string().nullish(),
  description: z.string().nullish(),
  date: z.iso.date().nullish(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  max_bookings: z.int().nullish(),
})

/**
 * EventBookingEntry
 *
 * A confirmed booking with slot_id, for the bulk event bookings endpoint.
 */
export const zEventBookingEntry = z
  .object({
    id: z.uuid(),
    duty_slot_id: z.uuid(),
    user_name: z.string().nullish(),
    user_phone_number: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'A confirmed booking with slot_id, for the bulk event bookings endpoint.',
  })

/**
 * EventCreate
 */
export const zEventCreate = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  created_by_id: z.uuid().nullish(),
  event_group_id: z.uuid().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
})

/**
 * EventFillRate
 */
export const zEventFillRate = z.object({
  event_id: z.uuid(),
  event_name: z.string(),
  total_capacity: z.int(),
  confirmed_bookings: z.int(),
  fill_rate: z.number(),
})

/**
 * EventGroupCreate
 */
export const zEventGroupCreate = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  created_by_id: z.uuid().nullish(),
})

/**
 * EventGroupRead
 */
export const zEventGroupRead = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  id: z.uuid(),
  created_by_id: z.uuid().nullish(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * EventGroupListResponse
 */
export const zEventGroupListResponse = z.object({
  items: z.array(zEventGroupRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * EventGroupUpdate
 */
export const zEventGroupUpdate = z.object({
  name: z.string().nullish(),
  description: z.string().nullish(),
  start_date: z.iso.date().nullish(),
  end_date: z.iso.date().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
})

/**
 * EventRead
 */
export const zEventRead = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  created_by_id: z.uuid().nullish(),
  event_group_id: z.uuid().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  slot_duration_minutes: z.int().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  people_per_slot: z.int().nullish(),
  schedule_overrides: z.array(z.record(z.string(), z.unknown())).nullish(),
})

/**
 * AddSlotsResponse
 */
export const zAddSlotsResponse = z.object({
  event: zEventRead,
  slots_added: z.int(),
})

/**
 * EventCreateWithSlotsResponse
 */
export const zEventCreateWithSlotsResponse = z.object({
  event: zEventRead,
  duty_slots_created: z.int(),
  event_group: zEventGroupRead.nullish(),
})

/**
 * EventListResponse
 */
export const zEventListResponse = z.object({
  items: z.array(zEventRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * EventUpdate
 */
export const zEventUpdate = z.object({
  name: z.string().nullish(),
  description: z.string().nullish(),
  start_date: z.iso.date().nullish(),
  end_date: z.iso.date().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  event_group_id: z.uuid().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
})

/**
 * ExcludedSlot
 */
export const zExcludedSlot = z.object({
  date: z.iso.date(),
  start_time: z.iso.time(),
  end_time: z.iso.time(),
})

/**
 * FeedSlotEntry
 *
 * Lightweight slot for the feed — no title/description, just booking info.
 */
export const zFeedSlotEntry = z
  .object({
    id: z.uuid(),
    date: z.iso.date(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
    max_bookings: z.int().optional().default(1),
    current_bookings: z.int().optional().default(0),
    is_booked_by_me: z.boolean().optional().default(false),
  })
  .register(z.globalRegistry, {
    description: 'Lightweight slot for the feed — no title/description, just booking info.',
  })

/**
 * FeedEventItem
 *
 * Event with view-dependent embedded data.
 */
export const zFeedEventItem = z
  .object({
    name: z.string(),
    description: z.string().nullish(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
    created_by_id: z.uuid().nullish(),
    event_group_id: z.uuid().nullish(),
    location: z.string().nullish(),
    category: z.string().nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    slot_duration_minutes: z.int().nullish(),
    default_start_time: z.iso.time().nullish(),
    default_end_time: z.iso.time().nullish(),
    people_per_slot: z.int().nullish(),
    schedule_overrides: z.array(z.record(z.string(), z.unknown())).nullish(),
    slots: z.array(zFeedSlotEntry).nullish(),
    slot_window_start: z.iso.date().nullish(),
    total_slots: z.int().nullish(),
    available_slots: z.int().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Event with view-dependent embedded data.',
  })

/**
 * EventFeedResponse
 */
export const zEventFeedResponse = z.object({
  items: z.array(zFeedEventItem),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * GlobalChannelSettingsRead
 */
export const zGlobalChannelSettingsRead = z.object({
  notify_email: z.boolean(),
  notify_push: z.boolean(),
  notify_telegram: z.boolean(),
})

/**
 * GlobalChannelSettingsUpdate
 */
export const zGlobalChannelSettingsUpdate = z.object({
  notify_email: z.boolean().nullish(),
  notify_push: z.boolean().nullish(),
  notify_telegram: z.boolean().nullish(),
})

/**
 * MyBookingsListResponse
 */
export const zMyBookingsListResponse = z.object({
  items: z.array(zBookingReadWithSlot),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * NotificationRead
 */
export const zNotificationRead = z.object({
  id: z.uuid(),
  recipient_id: z.uuid(),
  notification_type_code: z.string(),
  title: z.string(),
  body: z.string(),
  data: z.record(z.string(), z.union([z.string(), z.int()]).nullable()).nullish(),
  is_read: z.boolean(),
  read_at: z.iso.datetime().nullish(),
  channels_sent: z.array(z.string()),
  channels_failed: z.array(z.string()),
  created_at: z.iso.datetime(),
})

/**
 * NotificationListResponse
 */
export const zNotificationListResponse = z.object({
  items: z.array(zNotificationRead),
  total: z.int(),
  unread_count: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * NotificationSubscriptionCreate
 */
export const zNotificationSubscriptionCreate = z.object({
  notification_type_id: z.uuid(),
  email_enabled: z.boolean().optional().default(true),
  push_enabled: z.boolean().optional().default(true),
  telegram_enabled: z.boolean().optional().default(false),
  scope_type: z.enum(['global', 'event_group', 'event', 'duty_slot']).optional().default('global'),
  scope_id: z.uuid().nullish(),
  is_muted: z.boolean().optional().default(false),
})

/**
 * NotificationPreferencesBulkUpdate
 *
 * Full matrix of preferences sent from the frontend.
 */
export const zNotificationPreferencesBulkUpdate = z
  .object({
    preferences: z.array(zNotificationSubscriptionCreate),
  })
  .register(z.globalRegistry, {
    description: 'Full matrix of preferences sent from the frontend.',
  })

/**
 * NotificationSubscriptionRead
 */
export const zNotificationSubscriptionRead = z.object({
  id: z.uuid(),
  user_id: z.uuid(),
  notification_type_id: z.uuid(),
  email_enabled: z.boolean(),
  push_enabled: z.boolean(),
  telegram_enabled: z.boolean(),
  scope_type: z.string(),
  scope_id: z.uuid().nullish(),
  is_muted: z.boolean(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * NotificationSubscriptionUpdate
 */
export const zNotificationSubscriptionUpdate = z.object({
  email_enabled: z.boolean().nullish(),
  push_enabled: z.boolean().nullish(),
  telegram_enabled: z.boolean().nullish(),
  is_muted: z.boolean().nullish(),
})

/**
 * NotificationTypeRead
 */
export const zNotificationTypeRead = z.object({
  id: z.uuid(),
  code: z.string(),
  name: z.string(),
  description: z.string().nullish(),
  category: z.string(),
  is_admin_only: z.boolean(),
  default_channels: z.array(z.string()),
  is_active: z.boolean(),
  is_user_configurable: z.boolean(),
})

/**
 * ProfileInit
 *
 * Profile data from Auth0 ID token for user initialization.
 */
export const zProfileInit = z
  .object({
    email: z.email().nullish(),
    name: z.string().nullish(),
    nickname: z.string().nullish(),
    picture: z.string().nullish(),
    email_verified: z.boolean().nullish(),
    preferred_language: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Profile data from Auth0 ID token for user initialization.',
  })

/**
 * PushSubscriptionCreate
 */
export const zPushSubscriptionCreate = z.object({
  endpoint: z.string(),
  p256dh_key: z.string(),
  auth_key: z.string(),
  user_agent: z.string().nullish(),
})

/**
 * PushSubscriptionRead
 */
export const zPushSubscriptionRead = z.object({
  id: z.uuid(),
  endpoint: z.string(),
  user_agent: z.string().nullish(),
  created_at: z.iso.datetime(),
})

/**
 * ReminderOffsetEntry
 *
 * A single default reminder: offset + which channels to use.
 */
export const zReminderOffsetEntry = z
  .object({
    offset_minutes: z.union([
      z.literal(15),
      z.literal(30),
      z.literal(60),
      z.literal(120),
      z.literal(180),
      z.literal(360),
      z.literal(720),
      z.literal(1440),
      z.literal(2880),
    ]),
    channels: z
      .array(z.enum(['email', 'push', 'telegram']))
      .min(1)
      .optional()
      .default(['push']),
  })
  .register(z.globalRegistry, {
    description: 'A single default reminder: offset + which channels to use.',
  })

/**
 * DefaultReminderOffsetsRead
 */
export const zDefaultReminderOffsetsRead = z.object({
  default_reminder_offsets: z.array(zReminderOffsetEntry),
})

/**
 * DefaultReminderOffsetsUpdate
 */
export const zDefaultReminderOffsetsUpdate = z.object({
  default_reminder_offsets: z.array(zReminderOffsetEntry).max(5),
})

/**
 * ReportingOverviewStats
 */
export const zReportingOverviewStats = z.object({
  total_bookings: z.int(),
  confirmed_bookings: z.int(),
  cancelled_bookings: z.int(),
  cancellation_rate: z.number(),
  total_events: z.int(),
  total_slots: z.int(),
  total_slot_capacity: z.int(),
  filled_slots: z.int(),
  fill_rate: z.number(),
  active_volunteers: z.int(),
  total_volunteers: z.int(),
})

/**
 * ScheduleOverride
 */
export const zScheduleOverride = z.object({
  date: z.iso.date(),
  start_time: z.iso.time(),
  end_time: z.iso.time(),
})

/**
 * SelfApproveRequest
 */
export const zSelfApproveRequest = z.object({
  password: z.string().register(z.globalRegistry, {
    description: 'The approval password to verify',
  }),
})

/**
 * ShiftDatesRequest
 */
export const zShiftDatesRequest = z.object({
  new_start_date: z.iso.date(),
})

/**
 * SidebarBooking
 */
export const zSidebarBooking = z.object({
  id: z.uuid(),
  slot_id: z.uuid(),
  event_id: z.uuid(),
  slot_title: z.string(),
  slot_date: z.iso.date(),
  slot_start_time: z.iso.time().nullish(),
})

/**
 * SidebarEvent
 */
export const zSidebarEvent = z.object({
  id: z.uuid(),
  name: z.string(),
  status: z.string().optional().default('published'),
  open_slots: z.int(),
  next_slot_date: z.iso.date().nullish(),
  next_slot_start_time: z.iso.time().nullish(),
})

/**
 * SidebarEventGroup
 */
export const zSidebarEventGroup = z.object({
  id: z.uuid(),
  name: z.string(),
  status: z.string().optional().default('published'),
})

/**
 * SidebarResponse
 */
export const zSidebarResponse = z.object({
  event_groups: z.array(zSidebarEventGroup),
  events: z.array(zSidebarEvent),
  bookings: z.array(zSidebarBooking),
})

/**
 * SiteSettingsRead
 */
export const zSiteSettingsRead = z.object({
  has_approval_password: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether an approval password is currently configured',
    })
    .optional()
    .default(false),
})

/**
 * SiteSettingsUpdate
 */
export const zSiteSettingsUpdate = z.object({
  approval_password: z.string().nullish(),
})

/**
 * SlotBatchRead
 */
export const zSlotBatchRead = z.object({
  event_id: z.uuid(),
  label: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  slot_duration_minutes: z.int().nullish(),
  people_per_slot: z.int().nullish(),
  remainder_mode: z.enum(['drop', 'short', 'extend']).nullish().default('drop'),
  schedule_overrides: z.array(z.record(z.string(), z.unknown())).nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * SlotBookingEntry
 *
 * A confirmed booking for a slot, with basic user info.
 */
export const zSlotBookingEntry = z
  .object({
    id: z.uuid(),
    user_id: z.uuid(),
    user_name: z.string().nullish(),
    user_email: z.string().nullish(),
    user_picture: z.string().nullish(),
    user_phone_number: z.string().nullish(),
    notes: z.string().nullish(),
    created_at: z.iso.datetime(),
  })
  .register(z.globalRegistry, {
    description: 'A confirmed booking for a slot, with basic user info.',
  })

/**
 * SlotGenerationConfig
 */
export const zSlotGenerationConfig = z.object({
  default_start_time: z.iso.time(),
  default_end_time: z.iso.time(),
  slot_duration_minutes: z.int(),
  people_per_slot: z.int().optional().default(1),
  remainder_mode: z.enum(['drop', 'short', 'extend']).optional().default('drop'),
  overrides: z.array(zScheduleOverride).optional().default([]),
  excluded_slots: z.array(zExcludedSlot).optional().default([]),
})

/**
 * AddSlotsToEvent
 */
export const zAddSlotsToEvent = z.object({
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  schedule: zSlotGenerationConfig,
})

/**
 * EventCreateWithSlots
 */
export const zEventCreateWithSlots = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  location: z.string().nullish(),
  category: z.string().nullish(),
  event_group_id: z.uuid().nullish(),
  new_event_group: zEventGroupCreate.nullish(),
  schedule: zSlotGenerationConfig,
})

/**
 * EventUpdateWithSlots
 */
export const zEventUpdateWithSlots = z.object({
  name: z.string().nullish(),
  description: z.string().nullish(),
  start_date: z.iso.date().nullish(),
  end_date: z.iso.date().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  schedule: zSlotGenerationConfig,
})

/**
 * SlotRegenerationResult
 */
export const zSlotRegenerationResult = z.object({
  event: zEventRead,
  slots_added: z.int(),
  slots_removed: z.int(),
  slots_kept: z.int(),
  affected_bookings: z.array(zAffectedBookingInfo),
})

/**
 * SlotWindowResponse
 *
 * Response for the slot-window endpoint (next/prev day navigation).
 */
export const zSlotWindowResponse = z
  .object({
    slots: z.array(zFeedSlotEntry),
    start_date: z.iso.date(),
    days: z.int(),
  })
  .register(z.globalRegistry, {
    description: 'Response for the slot-window endpoint (next/prev day navigation).',
  })

/**
 * TelegramBindResponse
 */
export const zTelegramBindResponse = z.object({
  verification_code: z.string(),
  bot_username: z.string().nullish(),
  expires_at: z.iso.datetime(),
})

/**
 * TelegramBindingRead
 */
export const zTelegramBindingRead = z.object({
  id: z.uuid(),
  telegram_chat_id: z.string().nullish(),
  telegram_username: z.string().nullish(),
  is_verified: z.boolean(),
  created_at: z.iso.datetime(),
})

/**
 * TelegramChat
 */
export const zTelegramChat = z.object({
  id: z.int(),
  username: z.string().nullish(),
})

/**
 * TelegramConfigResponse
 */
export const zTelegramConfigResponse = z.object({
  bot_username: z.string().nullish(),
  is_configured: z.boolean(),
})

/**
 * TelegramLoginData
 *
 * Auth data returned by the Telegram Login Widget.
 */
export const zTelegramLoginData = z
  .object({
    id: z.int(),
    first_name: z.string().nullish(),
    last_name: z.string().nullish(),
    username: z.string().nullish(),
    photo_url: z.string().nullish(),
    auth_date: z.int(),
    hash: z.string(),
  })
  .register(z.globalRegistry, {
    description: 'Auth data returned by the Telegram Login Widget.',
  })

/**
 * TelegramMessage
 */
export const zTelegramMessage = z.object({
  text: z.string().nullish(),
  chat: zTelegramChat.nullish(),
})

/**
 * TelegramVerifyRequest
 */
export const zTelegramVerifyRequest = z.object({
  verification_code: z.string(),
  telegram_chat_id: z.string(),
  telegram_username: z.string().nullish(),
})

/**
 * TelegramWebhookUpdate
 *
 * Subset of the Telegram Bot API Update object we actually use.
 */
export const zTelegramWebhookUpdate = z
  .object({
    message: zTelegramMessage.nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Subset of the Telegram Bot API Update object we actually use.',
  })

/**
 * TestUserSeed
 */
export const zTestUserSeed = z.object({
  email: z.email(),
  name: z.string(),
  roles: z.array(z.string()).optional().default([]),
  is_active: z.boolean().optional().default(true),
  preferred_language: z.string().optional().default('en'),
})

/**
 * TopVolunteer
 */
export const zTopVolunteer = z.object({
  user_id: z.uuid(),
  name: z.string().nullable(),
  email: z.string().nullable(),
  booking_count: z.int(),
})

/**
 * ReportingResponse
 */
export const zReportingResponse = z.object({
  overview: zReportingOverviewStats,
  bookings_trend: z.array(zBookingsTrendPoint),
  top_volunteers: z.array(zTopVolunteer),
  category_breakdown: z.array(zCategoryBreakdown),
  bookings_by_hour: z.array(zBookingsByHour),
  event_fill_rates: z.array(zEventFillRate),
})

/**
 * UnreadCountResponse
 */
export const zUnreadCountResponse = z.object({
  unread_count: z.int(),
})

/**
 * UserAvailabilityDateInput
 */
export const zUserAvailabilityDateInput = z.object({
  date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
})

/**
 * UserAvailabilityCreate
 */
export const zUserAvailabilityCreate = z.object({
  availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
  notes: z.string().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  dates: z
    .array(z.union([z.iso.date(), zUserAvailabilityDateInput]))
    .optional()
    .default([]),
})

/**
 * UserAvailabilityDateRead
 */
export const zUserAvailabilityDateRead = z.object({
  id: z.uuid(),
  slot_date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
})

/**
 * UserAvailabilityRead
 */
export const zUserAvailabilityRead = z.object({
  availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
  notes: z.string().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  id: z.uuid(),
  user_id: z.uuid(),
  event_group_id: z.uuid(),
  available_dates: z.array(zUserAvailabilityDateRead).optional().default([]),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserAvailabilityWithUser
 *
 * Extended read schema for admin view — includes basic user info.
 */
export const zUserAvailabilityWithUser = z
  .object({
    availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
    notes: z.string().nullish(),
    default_start_time: z.iso.time().nullish(),
    default_end_time: z.iso.time().nullish(),
    id: z.uuid(),
    user_id: z.uuid(),
    event_group_id: z.uuid(),
    available_dates: z.array(zUserAvailabilityDateRead).optional().default([]),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    user_full_name: z.string().nullish(),
    user_email: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Extended read schema for admin view — includes basic user info.',
  })

/**
 * UserCounts
 */
export const zUserCounts = z.object({
  all: z.int(),
  active: z.int(),
  pending: z.int(),
  rejected: z.int(),
})

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  auth0_sub: z.string().register(z.globalRegistry, {
    description: 'Auth0 subject identifier',
  }),
  email: z.email().nullish(),
  name: z.string().nullish(),
  picture: z.string().nullish(),
  email_verified: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether the user's email is verified",
    })
    .optional()
    .default(false),
  roles: z
    .array(z.string())
    .register(z.globalRegistry, {
      description: 'List of role identifiers',
    })
    .optional(),
  is_active: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether the user is active',
    })
    .optional()
    .default(true),
  preferred_language: z
    .string()
    .register(z.globalRegistry, {
      description: 'Preferred language',
    })
    .optional()
    .default('en'),
})

/**
 * UserProfile
 */
export const zUserProfile = z.object({
  sub: z.string(),
  name: z.string().nullish(),
  nickname: z.string().nullish(),
  email: z.string().nullish(),
  picture: z.string().nullish(),
  bio: z.string().nullish(),
  phone_number: z.string().nullish(),
  preferred_language: z.string().optional().default('en'),
  email_verified: z.boolean().optional().default(false),
  roles: z
    .array(z.string())
    .register(z.globalRegistry, {
      description: "User's roles",
    })
    .optional(),
  is_admin: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether user has admin role',
    })
    .optional()
    .default(false),
  is_event_manager: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether user has event_manager role',
    })
    .optional()
    .default(false),
  is_active: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether user is active',
    })
    .optional()
    .default(true),
  rejection_reason: z.string().nullish(),
  managed_event_group_ids: z
    .array(z.uuid())
    .register(z.globalRegistry, {
      description: 'IDs of event groups this user manages (via event_group_managers)',
    })
    .optional(),
})

/**
 * UserProfileUpdate
 */
export const zUserProfileUpdate = z.object({
  name: z.string().max(100).nullish(),
  nickname: z.string().max(50).nullish(),
  picture: z.url().min(1).max(2083).nullish(),
  bio: z.string().max(500).nullish(),
  phone_number: z.string().max(30).nullish(),
  preferred_language: z
    .string()
    .regex(/^(en|de)$/)
    .nullish(),
})

/**
 * UserRead
 */
export const zUserRead = z.object({
  id: z.uuid(),
  auth0_sub: z.string(),
  email: z.email().nullish(),
  name: z.string().nullish(),
  picture: z.string().nullish(),
  phone_number: z.string().nullish(),
  preferred_language: z.string().optional().default('en'),
  roles: z.array(z.string()),
  is_active: z.boolean(),
  rejection_reason: z.string().nullish(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserListResponse
 */
export const zUserListResponse = z.object({
  items: z.array(zUserRead),
  skip: z.int(),
  limit: z.int(),
  counts: zUserCounts,
})

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
  email: z.email().nullish(),
  name: z.string().nullish(),
  roles: z.array(z.string()).nullish(),
  is_active: z.boolean().nullish(),
  rejection_reason: z.string().nullish(),
  preferred_language: z.string().nullish(),
})

export const zValidationErrorItem = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

export const zProblemDetails = z.object({
  type: z.url().default('about:blank'),
  code: z.string().optional(),
  title: z.string(),
  status: z.int(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  errors: z.array(zValidationErrorItem).optional(),
})

/**
 * Successful Response
 */
export const zUsersDeleteCurrentUserResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersUpdateUserProfileBody = zUserProfileUpdate

/**
 * Successful Response
 */
export const zUsersUpdateUserProfileResponse = zUserProfile

/**
 * Profile Init
 */
export const zUsersGetCurrentUserProfileBody = zProfileInit.nullable()

/**
 * Successful Response
 */
export const zUsersGetCurrentUserProfileResponse = zUserProfile

/**
 * Response Users-Get Approval Password Status
 *
 * Successful Response
 */
export const zUsersGetApprovalPasswordStatusResponse = z
  .record(z.string(), z.boolean())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zUsersSelfApproveBody = zSelfApproveRequest

/**
 * Successful Response
 */
export const zUsersSelfApproveResponse = zUserProfile

/**
 * Response Users-Get Auth0 Management Url
 *
 * Successful Response
 */
export const zUsersGetAuth0ManagementUrlResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zUsersListUsersQuery = z.object({
  q: z.string().nullish(),
  status_filter: z.enum(['all', 'active', 'pending', 'rejected']).optional().default('all'),
  skip: z.int().optional().default(0),
  limit: z.int().optional().default(20),
})

/**
 * Successful Response
 */
export const zUsersListUsersResponse = zUserListResponse

export const zUsersCreateUserBody = zUserCreate

/**
 * Successful Response
 */
export const zUsersCreateUserResponse = zUserRead

export const zUsersDeleteUserPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zUserRead

export const zUsersGetUserPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersGetUserResponse = zUserRead

export const zUsersUpdateUserBody = zUserUpdate

export const zUsersUpdateUserPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserRead

/**
 * Response Users-Export User Data
 *
 * Successful Response
 */
export const zUsersExportUserDataResponse = z
  .record(z.string(), z.unknown())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Successful Response
 */
export const zSettingsGetSiteSettingsResponse = zSiteSettingsRead

export const zSettingsUpdateSiteSettingsBody = zSiteSettingsUpdate

/**
 * Successful Response
 */
export const zSettingsUpdateSiteSettingsResponse = zSiteSettingsRead

export const zEventsEventFeedQuery = z.object({
  view: z.enum(['list', 'cards', 'calendar']).optional().default('list'),
  focus_mode: z.enum(['today', 'first_available']).optional().default('today'),
  search: z.string().nullish(),
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
  my_bookings: z.boolean().optional().default(false),
  days: z.int().gte(1).lte(31).optional().default(5),
})

/**
 * Successful Response
 */
export const zEventsEventFeedResponse = zEventFeedResponse

export const zEventsEventActiveDatesQuery = z.object({
  date_from: z.iso.date(),
  date_to: z.iso.date(),
})

/**
 * Response Events-Event Active Dates
 *
 * Successful Response
 */
export const zEventsEventActiveDatesResponse = z.array(z.iso.date()).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsGetSlotWindowPath = z.object({
  event_id: z.string(),
})

export const zEventsGetSlotWindowQuery = z.object({
  start_date: z.iso.date(),
  days: z.int().gte(1).lte(31).optional().default(5),
})

/**
 * Successful Response
 */
export const zEventsGetSlotWindowResponse = zSlotWindowResponse

export const zEventsListEventsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  search: z.string().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  my_bookings: z.boolean().optional().default(false),
})

/**
 * Successful Response
 */
export const zEventsListEventsResponse = zEventListResponse

export const zEventsCreateEventBody = zEventCreate

/**
 * Successful Response
 */
export const zEventsCreateEventResponse = zEventRead

export const zEventsDeleteEventPath = z.object({
  event_id: z.string(),
})

export const zEventsDeleteEventQuery = z.object({
  cancellation_reason: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zEventsDeleteEventResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsGetEventPath = z.object({
  event_id: z.string(),
})

/**
 * Successful Response
 */
export const zEventsGetEventResponse = zEventRead

export const zEventsUpdateEventBody = zEventUpdate

export const zEventsUpdateEventPath = z.object({
  event_id: z.string(),
})

/**
 * Successful Response
 */
export const zEventsUpdateEventResponse = zEventRead

export const zEventsListEventBookingsPath = z.object({
  event_id: z.string(),
})

/**
 * Response Events-List Event Bookings
 *
 * Successful Response
 */
export const zEventsListEventBookingsResponse = z
  .array(zEventBookingEntry)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsCreateEventWithSlotsBody = zEventCreateWithSlots

/**
 * Successful Response
 */
export const zEventsCreateEventWithSlotsResponse = zEventCreateWithSlotsResponse

export const zEventsAddSlotsToEventBody = zAddSlotsToEvent

export const zEventsAddSlotsToEventPath = z.object({
  event_id: z.string(),
})

/**
 * Successful Response
 */
export const zEventsAddSlotsToEventResponse = zAddSlotsResponse

export const zEventsRegenerateEventSlotsBody = zEventUpdateWithSlots

export const zEventsRegenerateEventSlotsPath = z.object({
  event_id: z.string(),
})

export const zEventsRegenerateEventSlotsQuery = z.object({
  dry_run: z.boolean().optional().default(false),
  batch_id: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zEventsRegenerateEventSlotsResponse = zSlotRegenerationResult

export const zEventsListBatchesPath = z.object({
  event_id: z.string(),
})

/**
 * Response Events-List Batches
 *
 * Successful Response
 */
export const zEventsListBatchesResponse = z.array(zSlotBatchRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsDeleteBatchPath = z.object({
  event_id: z.string(),
  batch_id: z.string(),
})

export const zEventsDeleteBatchQuery = z.object({
  cancellation_reason: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zEventsDeleteBatchResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zDutySlotsListDutySlotsQuery = z.object({
  event_id: z.string().nullish(),
  category: z.string().nullish(),
  search: z.string().nullish(),
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
})

/**
 * Successful Response
 */
export const zDutySlotsListDutySlotsResponse = zDutySlotListResponse

export const zDutySlotsCreateDutySlotBody = zDutySlotCreate

/**
 * Successful Response
 */
export const zDutySlotsCreateDutySlotResponse = zDutySlotRead

export const zDutySlotsDeleteDutySlotPath = z.object({
  slot_id: z.string(),
})

export const zDutySlotsDeleteDutySlotQuery = z.object({
  cancellation_reason: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zDutySlotsDeleteDutySlotResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zDutySlotsGetDutySlotPath = z.object({
  slot_id: z.string().nullable(),
})

/**
 * Successful Response
 */
export const zDutySlotsGetDutySlotResponse = zDutySlotRead

export const zDutySlotsUpdateDutySlotBody = zDutySlotUpdate

export const zDutySlotsUpdateDutySlotPath = z.object({
  slot_id: z.string(),
})

/**
 * Successful Response
 */
export const zDutySlotsUpdateDutySlotResponse = zDutySlotRead

export const zDutySlotsListSlotBookingsPath = z.object({
  slot_id: z.string(),
})

/**
 * Response Duty-Slots-List Slot Bookings
 *
 * Successful Response
 */
export const zDutySlotsListSlotBookingsResponse = z
  .array(zSlotBookingEntry)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zBookingsListMyBookingsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  status: z.string().nullish(),
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
})

/**
 * Successful Response
 */
export const zBookingsListMyBookingsResponse = zMyBookingsListResponse

export const zBookingsMyBookingActiveDatesQuery = z.object({
  date_from: z.iso.date(),
  date_to: z.iso.date(),
})

/**
 * Response Bookings-My Booking Active Dates
 *
 * Successful Response
 */
export const zBookingsMyBookingActiveDatesResponse = z
  .array(z.iso.date())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zBookingsCreateBookingBody = zBookingCreate

/**
 * Successful Response
 */
export const zBookingsCreateBookingResponse = zBookingRead

export const zBookingsCancelBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsCancelBookingResponse = zBookingRead

export const zBookingsGetBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsGetBookingResponse = zBookingRead

export const zBookingsUpdateBookingBody = zBookingUpdate

export const zBookingsUpdateBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsUpdateBookingResponse = zBookingRead

export const zBookingsDismissBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsDismissBookingResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zBookingRemindersGetReminderDefaultsResponse = zDefaultReminderOffsetsRead

export const zBookingRemindersUpdateReminderDefaultsBody = zDefaultReminderOffsetsUpdate

/**
 * Successful Response
 */
export const zBookingRemindersUpdateReminderDefaultsResponse = zDefaultReminderOffsetsRead

export const zBookingRemindersListBookingRemindersPath = z.object({
  booking_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zBookingRemindersListBookingRemindersResponse = zBookingReminderListResponse

export const zBookingRemindersAddBookingReminderBody = zBookingReminderCreate

export const zBookingRemindersAddBookingReminderPath = z.object({
  booking_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zBookingRemindersAddBookingReminderResponse = zBookingReminderRead

export const zBookingRemindersDeleteReminderPath = z.object({
  reminder_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zBookingRemindersDeleteReminderResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zCalendarDisableFeedResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Calendar-Get Feed Settings
 *
 * Successful Response
 */
export const zCalendarGetFeedSettingsResponse = zCalendarFeedRead.nullable()

/**
 * Successful Response
 */
export const zCalendarEnableFeedResponse = zCalendarFeedRead

/**
 * Successful Response
 */
export const zCalendarRegenerateFeedResponse = zCalendarFeedRead

export const zEventGroupsListEventGroupsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  search: z.string().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
})

/**
 * Successful Response
 */
export const zEventGroupsListEventGroupsResponse = zEventGroupListResponse

export const zEventGroupsCreateEventGroupBody = zEventGroupCreate

/**
 * Successful Response
 */
export const zEventGroupsCreateEventGroupResponse = zEventGroupRead

export const zEventGroupsDeleteEventGroupPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsDeleteEventGroupResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventGroupsGetEventGroupPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsGetEventGroupResponse = zEventGroupRead

export const zEventGroupsUpdateEventGroupBody = zEventGroupUpdate

export const zEventGroupsUpdateEventGroupPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsUpdateEventGroupResponse = zEventGroupRead

export const zEventGroupsGetEventDateBoundsPath = z.object({
  group_id: z.uuid(),
})

/**
 * Response Event-Groups-Get Event Date Bounds
 *
 * Successful Response
 */
export const zEventGroupsGetEventDateBoundsResponse = z
  .record(z.string(), z.iso.date().nullable())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventGroupsShiftEventGroupDatesBody = zShiftDatesRequest

export const zEventGroupsShiftEventGroupDatesPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsShiftEventGroupDatesResponse = zEventGroupRead

export const zEventGroupsListGroupAvailabilitiesPath = z.object({
  group_id: z.uuid(),
})

export const zEventGroupsListGroupAvailabilitiesQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(500).optional().default(200),
})

/**
 * Response Event-Groups-List Group Availabilities
 *
 * Successful Response
 */
export const zEventGroupsListGroupAvailabilitiesResponse = z
  .array(zUserAvailabilityWithUser)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventGroupsDeleteMyAvailabilityPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsDeleteMyAvailabilityResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventGroupsGetMyAvailabilityPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsGetMyAvailabilityResponse = zUserAvailabilityRead

export const zEventGroupsSetMyAvailabilityBody = zUserAvailabilityCreate

export const zEventGroupsSetMyAvailabilityPath = z.object({
  group_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsSetMyAvailabilityResponse = zUserAvailabilityRead

export const zEventGroupsListGroupManagersPath = z.object({
  group_id: z.uuid(),
})

/**
 * Response Event-Groups-List Group Managers
 *
 * Successful Response
 */
export const zEventGroupsListGroupManagersResponse = z.array(zUserRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventGroupsRemoveGroupManagerPath = z.object({
  group_id: z.uuid(),
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsRemoveGroupManagerResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventGroupsAssignGroupManagerPath = z.object({
  group_id: z.uuid(),
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventGroupsAssignGroupManagerResponse = zUserRead

/**
 * Response Notifications-List Notification Types
 *
 * Successful Response
 */
export const zNotificationsListNotificationTypesResponse = z
  .array(zNotificationTypeRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsNotificationStreamQuery = z.object({
  token: z.string().register(z.globalRegistry, {
    description: 'Bearer token for auth',
  }),
})

export const zNotificationsListNotificationsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(50),
  unread_only: z.boolean().optional().default(false),
})

/**
 * Successful Response
 */
export const zNotificationsListNotificationsResponse = zNotificationListResponse

/**
 * Successful Response
 */
export const zNotificationsGetUnreadCountResponse = zUnreadCountResponse

export const zNotificationsMarkNotificationReadPath = z.object({
  notification_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsMarkNotificationReadResponse = zNotificationRead

/**
 * Response Notifications-Mark All Notifications Read
 *
 * Successful Response
 */
export const zNotificationsMarkAllNotificationsReadResponse = z
  .record(z.string(), z.int())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Notifications-Dismiss All Notifications
 *
 * Successful Response
 */
export const zNotificationsDismissAllNotificationsResponse = z
  .record(z.string(), z.int())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsDismissNotificationPath = z.object({
  notification_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsDismissNotificationResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Notifications-List Preferences
 *
 * Successful Response
 */
export const zNotificationsListPreferencesResponse = z
  .array(zNotificationSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsCreatePreferenceBody = zNotificationSubscriptionCreate

/**
 * Successful Response
 */
export const zNotificationsCreatePreferenceResponse = zNotificationSubscriptionRead

export const zNotificationsBulkUpdatePreferencesBody = zNotificationPreferencesBulkUpdate

/**
 * Response Notifications-Bulk Update Preferences
 *
 * Successful Response
 */
export const zNotificationsBulkUpdatePreferencesResponse = z
  .array(zNotificationSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsDeletePreferencePath = z.object({
  preference_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsDeletePreferenceResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsUpdatePreferenceBody = zNotificationSubscriptionUpdate

export const zNotificationsUpdatePreferencePath = z.object({
  preference_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsUpdatePreferenceResponse = zNotificationSubscriptionRead

/**
 * Successful Response
 */
export const zNotificationsGetChannelSettingsResponse = zGlobalChannelSettingsRead

export const zNotificationsUpdateChannelSettingsBody = zGlobalChannelSettingsUpdate

/**
 * Successful Response
 */
export const zNotificationsUpdateChannelSettingsResponse = zGlobalChannelSettingsRead

/**
 * Response Notifications-List Push Subscriptions
 *
 * Successful Response
 */
export const zNotificationsListPushSubscriptionsResponse = z
  .array(zPushSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsRegisterPushSubscriptionBody = zPushSubscriptionCreate

/**
 * Successful Response
 */
export const zNotificationsRegisterPushSubscriptionResponse = zPushSubscriptionRead

export const zNotificationsRemovePushSubscriptionPath = z.object({
  subscription_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsRemovePushSubscriptionResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Notifications-Get Vapid Public Key
 *
 * Successful Response
 */
export const zNotificationsGetVapidPublicKeyResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Notifications-Send Test Push
 *
 * Successful Response
 */
export const zNotificationsSendTestPushResponse = z
  .record(z.string(), z.boolean())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Successful Response
 */
export const zNotificationsGetTelegramConfigResponse = zTelegramConfigResponse

/**
 * Successful Response
 */
export const zNotificationsUnbindTelegramResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Notifications-Get Telegram Binding
 *
 * Successful Response
 */
export const zNotificationsGetTelegramBindingResponse = zTelegramBindingRead.nullable()

export const zNotificationsTelegramLoginBody = zTelegramLoginData

/**
 * Successful Response
 */
export const zNotificationsTelegramLoginResponse = zTelegramBindingRead

/**
 * Successful Response
 */
export const zNotificationsStartTelegramBindingResponse = zTelegramBindResponse

export const zNotificationsVerifyTelegramBindingBody = zTelegramVerifyRequest

/**
 * Successful Response
 */
export const zNotificationsVerifyTelegramBindingResponse = zTelegramBindingRead

export const zNotificationsTelegramWebhookBody = zTelegramWebhookUpdate

/**
 * Response Notifications-Telegram Webhook
 *
 * Successful Response
 */
export const zNotificationsTelegramWebhookResponse = z
  .record(z.string(), z.boolean())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Successful Response
 */
export const zDashboardDashboardFeedResponse = zDashboardFeedResponse

/**
 * Successful Response
 */
export const zDashboardDashboardSidebarResponse = zSidebarResponse

export const zReportingReportingOverviewQuery = z.object({
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
})

/**
 * Successful Response
 */
export const zReportingReportingOverviewResponse = zReportingResponse

export const zReportingReportingExportQuery = z.object({
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
})

/**
 * Successful Response
 */
export const zDemoDataDeleteDemoDataResponse = zDemoDataDeletedResponse

export const zDemoDataCreateDemoDataBody = zDemoDataParams

/**
 * Successful Response
 */
export const zDemoDataCreateDemoDataResponse = zDemoDataCreatedResponse

/**
 * Response Debug-Start Log Capture
 *
 * Successful Response
 */
export const zDebugStartLogCaptureResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Debug-Stop Log Capture
 *
 * Successful Response
 */
export const zDebugStopLogCaptureResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zTestingSeedTestUserBody = zTestUserSeed

/**
 * Successful Response
 */
export const zTestingSeedTestUserResponse = zUserRead

/**
 * Response Testing-Reset Test Data
 *
 * Successful Response
 */
export const zTestingResetTestDataResponse = z
  .record(z.string(), z.int())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })
