import {
  type MaybeRefOrGetter,
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
  toValue,
  watch,
} from 'vue'

import { useI18n } from 'vue-i18n'

/** One product screenshot, as shown in a feature row and in the lightbox. */
export interface ScreenshotItem {
  /** File basename, without the `-light`/`-dark` suffix or extension. */
  name: string
  alt: string
  caption?: string
}

/** Which capture is being tried: the localised one, the English one, or neither. */
type Stage = 'locale' | 'fallback' | 'failed'

/**
 * Resolve the right screenshot file for the viewer's language and colour mode.
 *
 * Captures live at `public/screenshots/<lang>/<name>-<light|dark>.png` and are
 * regenerated by `just screenshots`. Two things this has to get right:
 *
 * - Dark mode is class-based, because a viewer can override their system
 *   setting, so the `dark` class on `<html>` decides rather than
 *   `prefers-color-scheme`.
 * - The two locale folders drift whenever a shot is added for one and forgotten
 *   for the other. A failed load falls back to the English capture instead of
 *   rendering a broken image, which is what German visitors used to get.
 */
export function useScreenshotSource(name: MaybeRefOrGetter<string>) {
  const { locale } = useI18n()

  const isDark = ref(false)
  let observer: MutationObserver | undefined

  function syncTheme() {
    isDark.value = document.documentElement.classList.contains('dark')
  }

  onMounted(() => {
    syncTheme()
    observer = new MutationObserver(syncTheme)
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] })
  })

  onBeforeUnmount(() => observer?.disconnect())

  const stage = ref<Stage>('locale')

  // A different file, language, or mode deserves a fresh attempt at the
  // localised capture rather than staying stuck on a previous fallback.
  watch(
    () => [toValue(name), locale.value, isDark.value],
    () => {
      stage.value = 'locale'
    },
  )

  const file = computed(() => `${toValue(name)}-${isDark.value ? 'dark' : 'light'}.png`)

  const src = computed(() =>
    stage.value === 'locale'
      ? `/screenshots/${locale.value}/${file.value}`
      : `/screenshots/en/${file.value}`,
  )

  function onError() {
    stage.value = stage.value === 'locale' && locale.value !== 'en' ? 'fallback' : 'failed'
  }

  const failed = computed(() => stage.value === 'failed')

  return { src, onError, failed, isDark }
}
