"""Add slot_batches table and batch_id to duty_slots

Revision ID: 20260310_0001
Revises: 20260309_0002
Create Date: 2026-03-10 21:09:32.910182

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "20260310_0001"
down_revision = "20260309_0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slot_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("default_start_time", sa.Time(), nullable=True),
        sa.Column("default_end_time", sa.Time(), nullable=True),
        sa.Column("slot_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("people_per_slot", sa.Integer(), nullable=True),
        sa.Column("remainder_mode", sa.String(), nullable=True),
        sa.Column("schedule_overrides", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_slot_batches_event_id"), "slot_batches", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_slot_batches_id"), "slot_batches", ["id"], unique=False)
    op.add_column("duty_slots", sa.Column("batch_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_duty_slots_batch_id"), "duty_slots", ["batch_id"], unique=False
    )
    op.create_foreign_key(None, "duty_slots", "slot_batches", ["batch_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "duty_slots", type_="foreignkey")
    op.drop_index(op.f("ix_duty_slots_batch_id"), table_name="duty_slots")
    op.drop_column("duty_slots", "batch_id")
    op.drop_index(op.f("ix_slot_batches_id"), table_name="slot_batches")
    op.drop_index(op.f("ix_slot_batches_event_id"), table_name="slot_batches")
    op.drop_table("slot_batches")
    # ### end Alembic commands ###
