"""Add event_group_managers table

Revision ID: 20260406_0001
Revises: 20260404_0001
Create Date: 2026-04-06 22:26:48.156463

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20260406_0001"
down_revision = "20260404_0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_group_managers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_group_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_group_id"], ["event_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "event_group_id", name="uq_event_group_manager"),
    )
    op.create_index(
        op.f("ix_event_group_managers_event_group_id"),
        "event_group_managers",
        ["event_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_group_managers_id"), "event_group_managers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_event_group_managers_user_id"),
        "event_group_managers",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "booking_reminders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "booking_reminders",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_index(
        op.f("ix_booking_reminders_id"), "booking_reminders", ["id"], unique=False
    )
    op.alter_column(
        "users", "email_verified", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("users", "bio")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("bio", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "users", "email_verified", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_index(op.f("ix_booking_reminders_id"), table_name="booking_reminders")
    op.alter_column(
        "booking_reminders",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "booking_reminders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_event_group_managers_user_id"), table_name="event_group_managers"
    )
    op.drop_index(op.f("ix_event_group_managers_id"), table_name="event_group_managers")
    op.drop_index(
        op.f("ix_event_group_managers_event_group_id"),
        table_name="event_group_managers",
    )
    op.drop_table("event_group_managers")
    # ### end Alembic commands ###
