"""soft_cancel_bookings_on_slot_deletion

Revision ID: 20260310_0002
Revises: 20260310_0001
Create Date: 2026-03-10 22:36:00.579988

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "20260310_0002"
down_revision = "20260310_0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("cancellation_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("cancelled_slot_title", sa.String(), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("cancelled_slot_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("cancelled_slot_start_time", sa.Time(), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("cancelled_slot_end_time", sa.Time(), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("cancelled_event_name", sa.String(), nullable=True)
    )
    op.alter_column("bookings", "duty_slot_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(
        op.f("bookings_duty_slot_id_fkey"), "bookings", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "bookings", "duty_slots", ["duty_slot_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        op.f("bookings_duty_slot_id_fkey"),
        "bookings",
        "duty_slots",
        ["duty_slot_id"],
        ["id"],
    )
    op.alter_column("bookings", "duty_slot_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("bookings", "cancelled_event_name")
    op.drop_column("bookings", "cancelled_slot_end_time")
    op.drop_column("bookings", "cancelled_slot_start_time")
    op.drop_column("bookings", "cancelled_slot_date")
    op.drop_column("bookings", "cancelled_slot_title")
    op.drop_column("bookings", "cancellation_reason")
    # ### end Alembic commands ###
