"""Add event groups and user availability

Revision ID: 20260308_0001
Revises: 20260301_0001
Create Date: 2026-03-08 14:22:20.767203

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "20260308_0001"
down_revision = "20260301_0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_groups_created_by_id"),
        "event_groups",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(op.f("ix_event_groups_id"), "event_groups", ["id"], unique=False)
    op.create_index(
        op.f("ix_event_groups_name"), "event_groups", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_event_groups_status"), "event_groups", ["status"], unique=False
    )
    op.create_table(
        "user_availabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_group_id", sa.Uuid(), nullable=False),
        sa.Column("availability_type", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_group_id"],
            ["event_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "event_group_id", name="uq_availability_user_group"
        ),
    )
    op.create_index(
        op.f("ix_user_availabilities_availability_type"),
        "user_availabilities",
        ["availability_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_availabilities_event_group_id"),
        "user_availabilities",
        ["event_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_availabilities_id"), "user_availabilities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_availabilities_user_id"),
        "user_availabilities",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_availability_dates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("availability_id", sa.Uuid(), nullable=False),
        sa.Column("slot_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["availability_id"],
            ["user_availabilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_availability_dates_availability_id"),
        "user_availability_dates",
        ["availability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_availability_dates_id"),
        "user_availability_dates",
        ["id"],
        unique=False,
    )
    op.add_column("events", sa.Column("event_group_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_events_event_group_id"), "events", ["event_group_id"], unique=False
    )
    op.create_foreign_key(None, "events", "event_groups", ["event_group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_index(op.f("ix_events_event_group_id"), table_name="events")
    op.drop_column("events", "event_group_id")
    op.drop_index(
        op.f("ix_user_availability_dates_id"), table_name="user_availability_dates"
    )
    op.drop_index(
        op.f("ix_user_availability_dates_availability_id"),
        table_name="user_availability_dates",
    )
    op.drop_table("user_availability_dates")
    op.drop_index(
        op.f("ix_user_availabilities_user_id"), table_name="user_availabilities"
    )
    op.drop_index(op.f("ix_user_availabilities_id"), table_name="user_availabilities")
    op.drop_index(
        op.f("ix_user_availabilities_event_group_id"), table_name="user_availabilities"
    )
    op.drop_index(
        op.f("ix_user_availabilities_availability_type"),
        table_name="user_availabilities",
    )
    op.drop_table("user_availabilities")
    op.drop_index(op.f("ix_event_groups_status"), table_name="event_groups")
    op.drop_index(op.f("ix_event_groups_name"), table_name="event_groups")
    op.drop_index(op.f("ix_event_groups_id"), table_name="event_groups")
    op.drop_index(op.f("ix_event_groups_created_by_id"), table_name="event_groups")
    op.drop_table("event_groups")
    # ### end Alembic commands ###
